"""`duct doctor completion` — emit shell completion activation scripts.

The command lives under ``doctor`` (alongside ``perf``) so the top-level command
list stays focused on everyday commands. The generated scripts are static and
mirror the current command tree.
"""

from __future__ import annotations

import textwrap

import click


def _zsh_completion_script() -> str:
    return textwrap.dedent("""\
        # duct shell completion (zsh)
        # Generated by: duct doctor completion zsh

        _duct_find_workspace_root() {
            local dir="$PWD"
            while [[ "$dir" != "/" ]]; do
                if [[ -f "$dir/toolkit/config.yaml" ]]; then
                    echo "$dir"
                    return 0
                fi
                dir="${dir:h}"
            done
            return 1
        }

        _duct_complete_ticket_key() {
            local root
            root="$(_duct_find_workspace_root)" || return
            local -a keys
            keys=( ${root}/[A-Z]*-[0-9]*(N/:t) )
            keys=( ${keys[@]%%[-_]*([^0-9])*} )
            # Extract unique KEY prefix (e.g. ERSC-1278 from ERSC-1278-some-slug)
            local -a unique_keys
            local entry
            for entry in ${root}/[A-Z]*-[0-9]*(N/); do
                entry="${entry:t}"
                if [[ "$entry" =~ '^([A-Z]+-[0-9]+)' ]]; then
                    unique_keys+=( "${match[1]}" )
                fi
            done
            compadd -a unique_keys
        }

        _duct_complete_repo_name() {
            local root
            root="$(_duct_find_workspace_root)" || return
            local cache="$root/.duct/cache/completions/repos.txt"
            [[ -f "$cache" ]] || return
            local -a repos
            repos=( ${(f)"$(< "$cache")"} )
            compadd -a repos
        }

        _duct_complete_session_id() {
            local sessions_dir="$HOME/.claude/sessions"
            [[ -d "$sessions_dir" ]] || return
            local -a ids
            local f pid sid
            for f in "$sessions_dir"/*.json(N); do
                pid="${${f:t}%.json}"
                kill -0 "$pid" 2>/dev/null || continue
                sid="$(grep -o '"sessionId"[[:space:]]*:[[:space:]]*"[^"]*"' "$f" 2>/dev/null | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/')"
                [[ -n "$sid" ]] && ids+=( "${sid:0:12}" )
            done
            compadd -a ids
        }

        _duct_complete_agent_name() {
            local root
            root="$(_duct_find_workspace_root)" || return
            [[ -d "$root/agents" ]] || return
            local -a agents
            local f name
            for f in "$root/agents"/*.md(N); do
                name="${${f:t}%.md}"
                agents+=( "$name" )
            done
            compadd -a agents
        }

        _duct() {
            local curcontext="$curcontext" state line
            typeset -A opt_args

            _arguments -C \\
                '--json[Output as JSON]' \\
                '--debug[Show debug information]' \\
                '--workspace-root=[Override workspace root]:path:_directories' \\
                '1:command:->cmd' \\
                '*::arg:->args'

            case "$state" in
            cmd)
                local -a commands=(
                    'activity:Aggregate an activity log across sources'
                    'agent:List and run workflow agents'
                    'archive:List and manage archived tickets'
                    'config:Manage workspace configuration'
                    'daemon:Manage the background daemon'
                    'doctor:Check workspace health (also: perf, completion)'
                    'orchestrate:Launch an orchestrator session'
                    'pr:List and inspect pull requests'
                    'session:View and manage Claude Code sessions'
                    'setup:Run the guided setup flow'
                    'status:Show workspace status overview'
                    'sync:Run sync sources'
                    'ticket:List and inspect tracked tickets'
                    'wiki:Inspect and maintain the workspace wiki'
                    'workspace:Manage ticket workspaces'
                )
                _describe 'command' commands
                ;;
            args)
                case "${line[1]}" in
                agent)
                    local -a subcmds=( 'list:List agents' 'run:Run an agent' )
                    _arguments '1:subcommand:((${(j: :)${subcmds[@]}}))' '*::arg:->agent_args'
                    if [[ "$state" == "agent_args" ]]; then
                        case "${line[1]}" in
                        run)
                            _arguments \\
                                '--ticket=[Ticket key]:ticket:_duct_complete_ticket_key' \\
                                '--repo=[Repo worktree]:repo:_duct_complete_repo_name' \\
                                '--skip-permissions[Skip permissions]' \\
                                '1:agent name:_duct_complete_agent_name'
                            ;;
                        esac
                    fi
                    ;;
                archive)
                    local -a subcmds=( 'add:Archive a ticket' 'list:List archived tickets' 'restore:Restore an archived ticket' )
                    _arguments '1:subcommand:((${(j: :)${subcmds[@]}}))' '*::arg:->archive_args'
                    if [[ "$state" == "archive_args" ]]; then
                        case "${line[1]}" in
                        add|restore)
                            _arguments '1:ticket key:_duct_complete_ticket_key'
                            ;;
                        esac
                    fi
                    ;;
                doctor)
                    local -a subcmds=( 'perf:Show timing statistics' 'completion:Print shell completion script' )
                    _arguments '1:subcommand:((${(j: :)${subcmds[@]}}))' '*::arg:->doctor_args'
                    if [[ "$state" == "doctor_args" ]]; then
                        case "${line[1]}" in
                        perf)
                            _arguments \\
                                '--limit=[Most recent N rows]:limit' \\
                                '--name=[Filter to a span name]:name' \\
                                '--tail[Print recent rows verbatim]'
                            ;;
                        completion)
                            _arguments '1:shell:(bash zsh fish)'
                            ;;
                        esac
                    fi
                    ;;
                orchestrate)
                    _arguments \\
                        '--ticket=[Focus on a ticket]:ticket key:_duct_complete_ticket_key' \\
                        '--dry-run[Print command without executing]' \\
                        '--sync[Run sync before launching]' \\
                        '--skip-permissions[Skip permissions]' \\
                        '--verbose[Stream activity]'
                    ;;
                pr)
                    local -a subcmds=( 'list:List pull requests' 'open:Open PR in browser' 'review:Review PRs (list, or <#> to deep-review)' )
                    _arguments '1:subcommand:((${(j: :)${subcmds[@]}}))' '*::arg:->pr_args'
                    if [[ "$state" == "pr_args" ]]; then
                        case "${line[1]}" in
                        list)
                            _arguments \\
                                '--all[Show all tickets]' \\
                                '--closed[Include terminal-status tickets]' \\
                                '--state=[Filter by PR state]:state:(open merged closed)' \\
                                '1:ticket key:_duct_complete_ticket_key'
                            ;;
                        review)
                            _arguments '1:subcommand or PR number:(list)'
                            ;;
                        esac
                    fi
                    ;;
                session)
                    local -a subcmds=(
                        'list:List sessions'
                        'show:Show session details'
                        'start:Launch a session'
                        'jump:Jump to session terminal tab'
                    )
                    _arguments '1:subcommand:((${(j: :)${subcmds[@]}}))' '*::arg:->session_args'
                    if [[ "$state" == "session_args" ]]; then
                        case "${line[1]}" in
                        show|jump)
                            _arguments '1:session id:_duct_complete_session_id'
                            ;;
                        start)
                            _arguments \\
                                '--prompt=[Initial prompt]:prompt' \\
                                '--repo=[Repo worktree]:repo' \\
                                '--skip-permissions[Skip permissions]' \\
                                '1:ticket key:_duct_complete_ticket_key'
                            ;;
                        esac
                    fi
                    ;;
                daemon)
                    local -a subcmds=( 'run:Run the loop in the foreground' 'install:Install + start the launchd agent' 'uninstall:Stop + remove the launchd agent' 'start:Start the installed daemon' 'stop:Stop the running daemon' 'status:Show daemon status' 'notify:Notify the user' )
                    _arguments '1:subcommand:((${(j: :)${subcmds[@]}}))' '*::arg:->daemon_args'
                    if [[ "$state" == "daemon_args" ]]; then
                        case "${line[1]}" in
                        notify)
                            _arguments \\
                                '--title=[Notification title]:title' \\
                                '--body=[Notification body]:body' \\
                                '--ticket=[Related ticket]:ticket key:_duct_complete_ticket_key' \\
                                '--url=[Click-to-open URL]:url'
                            ;;
                        esac
                    fi
                    ;;
                sync)
                    local -a subcmds=( 'ci:Sync CI' 'github:Sync GitHub' 'jira:Sync Jira' 'sessions:Sync sessions' 'status:Show sync status' 'workspace:Sync workspace' )
                    _arguments \\
                        '--force[Bypass staleness checks]' \\
                        '1:subcommand:((${(j: :)${subcmds[@]}}))'
                    ;;
                ticket)
                    local -a subcmds=( 'list:List tickets' 'open:Open in browser' 'status:Show ticket details' )
                    _arguments '1:subcommand:((${(j: :)${subcmds[@]}}))' '*::arg:->ticket_args'
                    if [[ "$state" == "ticket_args" ]]; then
                        case "${line[1]}" in
                        open|status)
                            _arguments '1:ticket key:_duct_complete_ticket_key'
                            ;;
                        list)
                            _arguments \\
                                '--category=[Filter by category]:category' \\
                                '--status=[Filter by status]:status' \\
                                '--sort=[Sort results]:sort:(key status category)'
                            ;;
                        esac
                    fi
                    ;;
                wiki)
                    local -a subcmds=( 'list:List entries' 'show:Show an entry' 'review:Run the maintainer' )
                    _arguments '1:subcommand:((${(j: :)${subcmds[@]}}))'
                    ;;
                workspace)
                    local -a subcmds=(
                        'add-repo:Add repo worktree'
                        'list-branches:List branches for a repo'
                        'list-repos:List available repos'
                        'path:Print workspace path'
                        'status:Show workspace health'
                    )
                    _arguments '1:subcommand:((${(j: :)${subcmds[@]}}))' '*::arg:->workspace_args'
                    if [[ "$state" == "workspace_args" ]]; then
                        case "${line[1]}" in
                        add-repo)
                            _arguments \\
                                '--branch=[Override branch name]:branch' \\
                                '1:ticket key:_duct_complete_ticket_key' \\
                                '2:repo name:_duct_complete_repo_name' \\
                                '3:base branch'
                            ;;
                        list-branches)
                            _arguments '1:repo name:_duct_complete_repo_name'
                            ;;
                        path)
                            _arguments '1:ticket key:_duct_complete_ticket_key'
                            ;;
                        esac
                    fi
                    ;;
                esac
                ;;
            esac
        }

        compdef _duct duct
    """)


def _bash_completion_script() -> str:
    return textwrap.dedent("""\
        # duct shell completion (bash)
        # Generated by: duct doctor completion bash

        _duct_find_workspace_root() {
            local dir="$PWD"
            while [[ "$dir" != "/" ]]; do
                if [[ -f "$dir/toolkit/config.yaml" ]]; then
                    echo "$dir"
                    return 0
                fi
                dir="$(dirname "$dir")"
            done
            return 1
        }

        _duct_complete_ticket_key() {
            local root
            root="$(_duct_find_workspace_root)" || return
            local cur="${COMP_WORDS[COMP_CWORD]}"
            local entries
            entries=$(ls -1d "$root"/[A-Z]*-[0-9]* 2>/dev/null | xargs -I{} basename {} | sed 's/^\\([A-Z]*-[0-9]*\\).*/\\1/' | sort -u)
            COMPREPLY=( $(compgen -W "$entries" -- "$cur") )
        }

        _duct_complete_repo_name() {
            local root
            root="$(_duct_find_workspace_root)" || return
            local cache="$root/.duct/cache/completions/repos.txt"
            [[ -f "$cache" ]] || return
            local cur="${COMP_WORDS[COMP_CWORD]}"
            COMPREPLY=( $(compgen -W "$(cat "$cache")" -- "$cur") )
        }

        _duct_complete_session_id() {
            local sessions_dir="$HOME/.claude/sessions"
            [[ -d "$sessions_dir" ]] || return
            local cur="${COMP_WORDS[COMP_CWORD]}"
            local ids=""
            local f pid sid
            for f in "$sessions_dir"/*.json; do
                [[ -f "$f" ]] || continue
                pid="$(basename "$f" .json)"
                kill -0 "$pid" 2>/dev/null || continue
                sid="$(grep -o '"sessionId"[[:space:]]*:[[:space:]]*"[^"]*"' "$f" 2>/dev/null | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/')"
                [[ -n "$sid" ]] && ids="$ids ${sid:0:12}"
            done
            COMPREPLY=( $(compgen -W "$ids" -- "$cur") )
        }

        _duct_complete_agent_name() {
            local root
            root="$(_duct_find_workspace_root)" || return
            [[ -d "$root/agents" ]] || return
            local cur="${COMP_WORDS[COMP_CWORD]}"
            local names=""
            local f
            for f in "$root/agents"/*.md; do
                [[ -f "$f" ]] || continue
                names="$names $(basename "$f" .md)"
            done
            COMPREPLY=( $(compgen -W "$names" -- "$cur") )
        }

        _duct() {
            local cur prev words cword
            _init_completion || return

            local commands="activity agent archive config daemon doctor init orchestrate pr session setup status sync ticket wiki workspace"

            if [[ $cword -eq 1 ]]; then
                COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
                return
            fi

            local cmd="${words[1]}"
            case "$cmd" in
            agent)
                if [[ $cword -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "list run" -- "$cur") )
                elif [[ "${words[2]}" == "run" ]]; then
                    if [[ "$prev" == "--ticket" ]]; then
                        _duct_complete_ticket_key
                    elif [[ "$prev" == "--repo" ]]; then
                        _duct_complete_repo_name
                    elif [[ $cword -eq 3 ]]; then
                        _duct_complete_agent_name
                    else
                        COMPREPLY=( $(compgen -W "--ticket --repo --skip-permissions" -- "$cur") )
                    fi
                fi
                ;;
            archive)
                if [[ $cword -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "add list restore" -- "$cur") )
                elif [[ $cword -eq 3 ]]; then
                    case "${words[2]}" in
                    add|restore) _duct_complete_ticket_key ;;
                    esac
                fi
                ;;
            doctor)
                if [[ $cword -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "perf completion" -- "$cur") )
                elif [[ "${words[2]}" == "completion" && $cword -eq 3 ]]; then
                    COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
                elif [[ "${words[2]}" == "perf" ]]; then
                    COMPREPLY=( $(compgen -W "--limit --name --tail" -- "$cur") )
                fi
                ;;
            daemon)
                if [[ $cword -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "run install uninstall start stop status notify" -- "$cur") )
                elif [[ "${words[2]}" == "notify" ]]; then
                    if [[ "$prev" == "--ticket" ]]; then
                        _duct_complete_ticket_key
                    else
                        COMPREPLY=( $(compgen -W "--title --body --ticket --url" -- "$cur") )
                    fi
                fi
                ;;
            orchestrate)
                if [[ "$prev" == "--ticket" ]]; then
                    _duct_complete_ticket_key
                else
                    COMPREPLY=( $(compgen -W "--ticket --dry-run --sync --skip-permissions --verbose" -- "$cur") )
                fi
                ;;
            pr)
                if [[ $cword -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "list open review" -- "$cur") )
                elif [[ $cword -eq 3 ]]; then
                    case "${words[2]}" in
                    list) _duct_complete_ticket_key ;;
                    review) COMPREPLY=( $(compgen -W "list" -- "$cur") ) ;;
                    esac
                fi
                ;;
            session)
                if [[ $cword -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "list show start jump" -- "$cur") )
                elif [[ $cword -eq 3 ]]; then
                    case "${words[2]}" in
                    show|jump) _duct_complete_session_id ;;
                    start) _duct_complete_ticket_key ;;
                    esac
                fi
                ;;
            sync)
                [[ $cword -eq 2 ]] && COMPREPLY=( $(compgen -W "ci github jira sessions status workspace --force" -- "$cur") )
                ;;
            ticket)
                if [[ $cword -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "list open status" -- "$cur") )
                elif [[ $cword -eq 3 ]]; then
                    case "${words[2]}" in
                    open|status) _duct_complete_ticket_key ;;
                    esac
                fi
                ;;
            wiki)
                if [[ $cword -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "list show review" -- "$cur") )
                fi
                ;;
            workspace)
                if [[ $cword -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "add-repo list-branches list-repos path status" -- "$cur") )
                elif [[ $cword -ge 3 ]]; then
                    case "${words[2]}" in
                    add-repo)
                        case $cword in
                        3) _duct_complete_ticket_key ;;
                        4) _duct_complete_repo_name ;;
                        esac
                        ;;
                    list-branches)
                        [[ $cword -eq 3 ]] && _duct_complete_repo_name
                        ;;
                    path)
                        [[ $cword -eq 3 ]] && _duct_complete_ticket_key
                        ;;
                    esac
                fi
                ;;
            esac
        }

        complete -o default -F _duct duct
    """)


def _fish_completion_script() -> str:
    return textwrap.dedent("""\
        # duct shell completion (fish)
        # Generated by: duct doctor completion fish

        function __duct_find_workspace_root
            set -l dir (pwd)
            while test "$dir" != "/"
                if test -f "$dir/toolkit/config.yaml"
                    echo "$dir"
                    return 0
                end
                set dir (dirname "$dir")
            end
            return 1
        end

        function __duct_complete_ticket_key
            set -l root (__duct_find_workspace_root); or return
            for entry in $root/[A-Z]*-[0-9]*
                test -d "$entry"; or continue
                set -l name (basename "$entry")
                string match -r '^([A-Z]+-[0-9]+)' -- "$name" | head -1
            end | sort -u
        end

        function __duct_complete_repo_name
            set -l root (__duct_find_workspace_root); or return
            set -l cache "$root/.duct/cache/completions/repos.txt"
            test -f "$cache"; or return
            cat "$cache"
        end

        function __duct_complete_session_id
            set -l sessions_dir "$HOME/.claude/sessions"
            test -d "$sessions_dir"; or return
            for f in $sessions_dir/*.json
                test -f "$f"; or continue
                set -l pid (basename "$f" .json)
                kill -0 "$pid" 2>/dev/null; or continue
                set -l sid (grep -o '"sessionId"[[:space:]]*:[[:space:]]*"[^"]*"' "$f" 2>/dev/null | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/')
                test -n "$sid"; and echo (string sub -l 12 "$sid")
            end
        end

        function __duct_complete_agent_name
            set -l root (__duct_find_workspace_root); or return
            test -d "$root/agents"; or return
            for f in $root/agents/*.md
                test -f "$f"; or continue
                basename "$f" .md
            end
        end

        # Disable default file completions
        complete -c duct -f

        # Top-level commands
        complete -c duct -n '__fish_use_subcommand' -a 'activity' -d 'Aggregate activity log'
        complete -c duct -n '__fish_use_subcommand' -a 'agent' -d 'List and run workflow agents'
        complete -c duct -n '__fish_use_subcommand' -a 'archive' -d 'Manage archived tickets'
        complete -c duct -n '__fish_use_subcommand' -a 'config' -d 'Manage configuration'
        complete -c duct -n '__fish_use_subcommand' -a 'daemon' -d 'Manage the background daemon'
        complete -c duct -n '__fish_use_subcommand' -a 'doctor' -d 'Check workspace health'
        complete -c duct -n '__fish_use_subcommand' -a 'orchestrate' -d 'Launch orchestrator'
        complete -c duct -n '__fish_use_subcommand' -a 'pr' -d 'List and inspect pull requests'
        complete -c duct -n '__fish_use_subcommand' -a 'session' -d 'Manage Claude sessions'
        complete -c duct -n '__fish_use_subcommand' -a 'setup' -d 'Run the guided setup flow'
        complete -c duct -n '__fish_use_subcommand' -a 'status' -d 'Show status overview'
        complete -c duct -n '__fish_use_subcommand' -a 'sync' -d 'Run sync sources'
        complete -c duct -n '__fish_use_subcommand' -a 'ticket' -d 'List and inspect tickets'
        complete -c duct -n '__fish_use_subcommand' -a 'wiki' -d 'Inspect and maintain the workspace wiki'
        complete -c duct -n '__fish_use_subcommand' -a 'workspace' -d 'Manage workspaces'

        # ticket subcommands
        complete -c duct -n '__fish_seen_subcommand_from ticket; and not __fish_seen_subcommand_from list open status' -a 'list open status'
        complete -c duct -n '__fish_seen_subcommand_from ticket; and __fish_seen_subcommand_from open status' -a '(__duct_complete_ticket_key)'

        # pr subcommands
        complete -c duct -n '__fish_seen_subcommand_from pr; and not __fish_seen_subcommand_from list open review' -a 'list open review'
        complete -c duct -n '__fish_seen_subcommand_from pr; and __fish_seen_subcommand_from list' -a '(__duct_complete_ticket_key)'
        complete -c duct -n '__fish_seen_subcommand_from pr; and __fish_seen_subcommand_from review; and not __fish_seen_subcommand_from list' -a 'list'

        # agent subcommands
        complete -c duct -n '__fish_seen_subcommand_from agent; and not __fish_seen_subcommand_from list run' -a 'list run'
        complete -c duct -n '__fish_seen_subcommand_from agent; and __fish_seen_subcommand_from run' -a '(__duct_complete_agent_name)'
        complete -c duct -n '__fish_seen_subcommand_from agent; and __fish_seen_subcommand_from run' -l ticket -a '(__duct_complete_ticket_key)'
        complete -c duct -n '__fish_seen_subcommand_from agent; and __fish_seen_subcommand_from run' -l repo -a '(__duct_complete_repo_name)'
        complete -c duct -n '__fish_seen_subcommand_from agent; and __fish_seen_subcommand_from run' -l skip-permissions

        # archive subcommands
        complete -c duct -n '__fish_seen_subcommand_from archive; and not __fish_seen_subcommand_from add list restore' -a 'add list restore'
        complete -c duct -n '__fish_seen_subcommand_from archive; and __fish_seen_subcommand_from add restore' -a '(__duct_complete_ticket_key)'

        # session subcommands
        complete -c duct -n '__fish_seen_subcommand_from session; and not __fish_seen_subcommand_from list show start jump' -a 'list show start jump'
        complete -c duct -n '__fish_seen_subcommand_from session; and __fish_seen_subcommand_from show jump' -a '(__duct_complete_session_id)'
        complete -c duct -n '__fish_seen_subcommand_from session; and __fish_seen_subcommand_from start' -a '(__duct_complete_ticket_key)'

        # sync subcommands
        complete -c duct -n '__fish_seen_subcommand_from sync; and not __fish_seen_subcommand_from ci github jira sessions status workspace' -a 'ci github jira sessions status workspace'

        # daemon subcommands
        complete -c duct -n '__fish_seen_subcommand_from daemon; and not __fish_seen_subcommand_from run install uninstall start stop status notify' -a 'run install uninstall start stop status notify'

        # daemon notify options
        complete -c duct -n '__fish_seen_subcommand_from daemon; and __fish_seen_subcommand_from notify' -l title
        complete -c duct -n '__fish_seen_subcommand_from daemon; and __fish_seen_subcommand_from notify' -l body
        complete -c duct -n '__fish_seen_subcommand_from daemon; and __fish_seen_subcommand_from notify' -l ticket -a '(__duct_complete_ticket_key)'
        complete -c duct -n '__fish_seen_subcommand_from daemon; and __fish_seen_subcommand_from notify' -l url

        # doctor subcommands
        complete -c duct -n '__fish_seen_subcommand_from doctor; and not __fish_seen_subcommand_from perf completion' -a 'perf completion'
        complete -c duct -n '__fish_seen_subcommand_from doctor; and __fish_seen_subcommand_from completion' -a 'bash zsh fish'
        complete -c duct -n '__fish_seen_subcommand_from doctor; and __fish_seen_subcommand_from perf' -l limit
        complete -c duct -n '__fish_seen_subcommand_from doctor; and __fish_seen_subcommand_from perf' -l name
        complete -c duct -n '__fish_seen_subcommand_from doctor; and __fish_seen_subcommand_from perf' -l tail

        # orchestrate options
        complete -c duct -n '__fish_seen_subcommand_from orchestrate' -l ticket -a '(__duct_complete_ticket_key)'
        complete -c duct -n '__fish_seen_subcommand_from orchestrate' -l dry-run
        complete -c duct -n '__fish_seen_subcommand_from orchestrate' -l sync
        complete -c duct -n '__fish_seen_subcommand_from orchestrate' -l skip-permissions
        complete -c duct -n '__fish_seen_subcommand_from orchestrate' -s v -l verbose

        # wiki subcommands
        complete -c duct -n '__fish_seen_subcommand_from wiki; and not __fish_seen_subcommand_from list show review' -a 'list show review'

        # workspace subcommands
        complete -c duct -n '__fish_seen_subcommand_from workspace; and not __fish_seen_subcommand_from add-repo list-branches list-repos path status' -a 'add-repo list-branches list-repos path status'
        complete -c duct -n '__fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from path' -a '(__duct_complete_ticket_key)'
        complete -c duct -n '__fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from add-repo' -a '(__duct_complete_ticket_key)'
        complete -c duct -n '__fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from add-repo' -a '(__duct_complete_repo_name)'
        complete -c duct -n '__fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from list-branches' -a '(__duct_complete_repo_name)'
    """)


@click.command()
@click.argument("shell", type=click.Choice(["bash", "zsh", "fish"]))
def completion(shell: str) -> None:
    """Print shell completion activation script.

    Add the output to your shell profile to enable tab completion:

        eval "$(duct doctor completion zsh)"
    """
    generators = {
        "bash": _bash_completion_script,
        "zsh": _zsh_completion_script,
        "fish": _fish_completion_script,
    }
    click.echo(generators[shell]())
