"""CLI entry point for duct."""

import importlib
import textwrap

import click

COMMANDS = {
    "add-repo": "duct.cli.workspace_cmd:add_repo",
    "archive": "duct.cli.archive_cmd:archive",
    "config": "duct.cli.config_cmd:config",
    "doctor": "duct.cli.doctor_cmd:doctor",
    "init": "duct.cli.init_cmd:init",
    "orchestrate": "duct.cli.orchestrate_cmd:orchestrate",
    "priority": "duct.cli.priority_cmd:priority",
    "session": "duct.cli.session_cmd:session",
    "status": "duct.cli.status_cmd:status",
    "sync": "duct.cli.sync_cmd:sync",
    "ticket": "duct.cli.ticket_cmd:ticket",
    "workspace": "duct.cli.workspace_cmd:workspace",
}


def _zsh_completion_script() -> str:
    return textwrap.dedent("""\
        # duct shell completion (zsh)
        # Generated by: duct completion zsh

        _duct_find_workspace_root() {
            local dir="$PWD"
            while [[ "$dir" != "/" ]]; do
                if [[ -f "$dir/config.yaml" ]]; then
                    echo "$dir"
                    return 0
                fi
                dir="${dir:h}"
            done
            return 1
        }

        _duct_complete_ticket_key() {
            local root
            root="$(_duct_find_workspace_root)" || return
            local -a keys
            keys=( ${root}/[A-Z]*-[0-9]*(N/:t) )
            keys=( ${keys[@]%%[-_]*([^0-9])*} )
            # Extract unique KEY prefix (e.g. ERSC-1278 from ERSC-1278-some-slug)
            local -a unique_keys
            local entry
            for entry in ${root}/[A-Z]*-[0-9]*(N/); do
                entry="${entry:t}"
                if [[ "$entry" =~ '^([A-Z]+-[0-9]+)' ]]; then
                    unique_keys+=( "${match[1]}" )
                fi
            done
            compadd -a unique_keys
        }

        _duct_complete_repo_name() {
            local root
            root="$(_duct_find_workspace_root)" || return
            local cache="$root/.cache/completions/repos.txt"
            [[ -f "$cache" ]] || return
            local -a repos
            repos=( ${(f)"$(< "$cache")"} )
            compadd -a repos
        }

        _duct_complete_session_id() {
            local sessions_dir="$HOME/.claude/sessions"
            [[ -d "$sessions_dir" ]] || return
            local -a ids
            local f pid sid
            for f in "$sessions_dir"/*.json(N); do
                pid="${${f:t}%.json}"
                kill -0 "$pid" 2>/dev/null || continue
                sid="$(grep -o '"sessionId"[[:space:]]*:[[:space:]]*"[^"]*"' "$f" 2>/dev/null | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/')"
                [[ -n "$sid" ]] && ids+=( "${sid:0:12}" )
            done
            compadd -a ids
        }

        _duct() {
            local curcontext="$curcontext" state line
            typeset -A opt_args

            _arguments -C \\
                '--json[Output as JSON]' \\
                '--debug[Show debug information]' \\
                '--workspace-root=[Override workspace root]:path:_directories' \\
                '1:command:->cmd' \\
                '*::arg:->args'

            case "$state" in
            cmd)
                local -a commands=(
                    'add-repo:Add a repo worktree to a ticket workspace'
                    'archive:List and manage archived tickets'
                    'completion:Print shell completion activation script'
                    'config:Manage workspace configuration'
                    'doctor:Check workspace health'
                    'init:Create workspace skeleton'
                    'orchestrate:Launch an orchestrator session'
                    'priority:View or edit the priority list'
                    'session:View and manage Claude Code sessions'
                    'status:Show workspace status overview'
                    'sync:Run sync sources'
                    'ticket:List and inspect tracked tickets'
                    'workspace:Manage ticket workspaces'
                )
                _describe 'command' commands
                ;;
            args)
                case "${line[1]}" in
                add-repo)
                    _arguments \\
                        '--branch=[Override feature branch name]:branch' \\
                        '1:ticket key:_duct_complete_ticket_key' \\
                        '2:repo name:_duct_complete_repo_name' \\
                        '3:base branch'
                    ;;
                archive)
                    local -a subcmds=( 'add:Archive a ticket' 'list:List archived tickets' 'restore:Restore an archived ticket' )
                    _arguments '1:subcommand:((${(j: :)${subcmds[@]}}))' '*::arg:->archive_args'
                    if [[ "$state" == "archive_args" ]]; then
                        case "${line[1]}" in
                        add|restore)
                            _arguments '1:ticket key:_duct_complete_ticket_key'
                            ;;
                        esac
                    fi
                    ;;
                completion)
                    _arguments '1:shell:(bash zsh fish)'
                    ;;
                orchestrate)
                    _arguments \\
                        '--ticket=[Focus on a ticket]:ticket key:_duct_complete_ticket_key' \\
                        '--dry-run[Print command without executing]' \\
                        '--sync[Run sync before launching]' \\
                        '--skip-permissions[Skip permissions]' \\
                        '--verbose[Stream activity]'
                    ;;
                priority)
                    local -a subcmds=( 'add:Add a ticket to priority list' )
                    _arguments '1:subcommand:((${(j: :)${subcmds[@]}}))' '*::arg:->priority_args'
                    if [[ "$state" == "priority_args" ]]; then
                        case "${line[1]}" in
                        add)
                            _arguments '1:ticket key:_duct_complete_ticket_key' '*:note'
                            ;;
                        esac
                    fi
                    ;;
                session)
                    local -a subcmds=(
                        'list:List sessions'
                        'show:Show session details'
                        'start:Launch a session'
                        'jump:Jump to session terminal tab'
                    )
                    _arguments '1:subcommand:((${(j: :)${subcmds[@]}}))' '*::arg:->session_args'
                    if [[ "$state" == "session_args" ]]; then
                        case "${line[1]}" in
                        show|jump)
                            _arguments '1:session id:_duct_complete_session_id'
                            ;;
                        start)
                            _arguments \\
                                '--prompt=[Initial prompt]:prompt' \\
                                '--repo=[Repo worktree]:repo' \\
                                '--skip-permissions[Skip permissions]' \\
                                '1:ticket key:_duct_complete_ticket_key'
                            ;;
                        esac
                    fi
                    ;;
                sync)
                    local -a subcmds=( 'ci:Sync CI' 'github:Sync GitHub' 'jira:Sync Jira' 'sessions:Sync sessions' 'status:Show sync status' 'workspace:Sync workspace' )
                    _arguments \\
                        '--force[Bypass staleness checks]' \\
                        '1:subcommand:((${(j: :)${subcmds[@]}}))'
                    ;;
                ticket)
                    local -a subcmds=( 'list:List tickets' 'open:Open in browser' 'show:Show ticket details' )
                    _arguments '1:subcommand:((${(j: :)${subcmds[@]}}))' '*::arg:->ticket_args'
                    if [[ "$state" == "ticket_args" ]]; then
                        case "${line[1]}" in
                        open|show)
                            _arguments '1:ticket key:_duct_complete_ticket_key'
                            ;;
                        list)
                            _arguments \\
                                '--category=[Filter by category]:category' \\
                                '--status=[Filter by status]:status' \\
                                '--sort=[Sort results]:sort:(priority key status category)'
                            ;;
                        esac
                    fi
                    ;;
                workspace)
                    local -a subcmds=( 'add-repo:Add repo worktree' 'path:Print workspace path' 'status:Show workspace health' )
                    _arguments '1:subcommand:((${(j: :)${subcmds[@]}}))' '*::arg:->workspace_args'
                    if [[ "$state" == "workspace_args" ]]; then
                        case "${line[1]}" in
                        add-repo)
                            _arguments \\
                                '--branch=[Override branch name]:branch' \\
                                '1:ticket key:_duct_complete_ticket_key' \\
                                '2:repo name:_duct_complete_repo_name' \\
                                '3:base branch'
                            ;;
                        path)
                            _arguments '1:ticket key:_duct_complete_ticket_key'
                            ;;
                        esac
                    fi
                    ;;
                esac
                ;;
            esac
        }

        compdef _duct duct
    """)


def _bash_completion_script() -> str:
    return textwrap.dedent("""\
        # duct shell completion (bash)
        # Generated by: duct completion bash

        _duct_find_workspace_root() {
            local dir="$PWD"
            while [[ "$dir" != "/" ]]; do
                if [[ -f "$dir/config.yaml" ]]; then
                    echo "$dir"
                    return 0
                fi
                dir="$(dirname "$dir")"
            done
            return 1
        }

        _duct_complete_ticket_key() {
            local root
            root="$(_duct_find_workspace_root)" || return
            local cur="${COMP_WORDS[COMP_CWORD]}"
            local entries
            entries=$(ls -1d "$root"/[A-Z]*-[0-9]* 2>/dev/null | xargs -I{} basename {} | sed 's/^\\([A-Z]*-[0-9]*\\).*/\\1/' | sort -u)
            COMPREPLY=( $(compgen -W "$entries" -- "$cur") )
        }

        _duct_complete_repo_name() {
            local root
            root="$(_duct_find_workspace_root)" || return
            local cache="$root/.cache/completions/repos.txt"
            [[ -f "$cache" ]] || return
            local cur="${COMP_WORDS[COMP_CWORD]}"
            COMPREPLY=( $(compgen -W "$(cat "$cache")" -- "$cur") )
        }

        _duct_complete_session_id() {
            local sessions_dir="$HOME/.claude/sessions"
            [[ -d "$sessions_dir" ]] || return
            local cur="${COMP_WORDS[COMP_CWORD]}"
            local ids=""
            local f pid sid
            for f in "$sessions_dir"/*.json; do
                [[ -f "$f" ]] || continue
                pid="$(basename "$f" .json)"
                kill -0 "$pid" 2>/dev/null || continue
                sid="$(grep -o '"sessionId"[[:space:]]*:[[:space:]]*"[^"]*"' "$f" 2>/dev/null | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/')"
                [[ -n "$sid" ]] && ids="$ids ${sid:0:12}"
            done
            COMPREPLY=( $(compgen -W "$ids" -- "$cur") )
        }

        _duct() {
            local cur prev words cword
            _init_completion || return

            local commands="add-repo archive completion config doctor init orchestrate priority session status sync ticket workspace"

            if [[ $cword -eq 1 ]]; then
                COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
                return
            fi

            local cmd="${words[1]}"
            case "$cmd" in
            add-repo)
                case $cword in
                2) _duct_complete_ticket_key ;;
                3) _duct_complete_repo_name ;;
                esac
                ;;
            archive)
                if [[ $cword -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "add list restore" -- "$cur") )
                elif [[ $cword -eq 3 ]]; then
                    case "${words[2]}" in
                    add|restore) _duct_complete_ticket_key ;;
                    esac
                fi
                ;;
            completion)
                [[ $cword -eq 2 ]] && COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
                ;;
            orchestrate)
                if [[ "$prev" == "--ticket" ]]; then
                    _duct_complete_ticket_key
                else
                    COMPREPLY=( $(compgen -W "--ticket --dry-run --sync --skip-permissions --verbose" -- "$cur") )
                fi
                ;;
            priority)
                if [[ $cword -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "add" -- "$cur") )
                elif [[ $cword -eq 3 && "${words[2]}" == "add" ]]; then
                    _duct_complete_ticket_key
                fi
                ;;
            session)
                if [[ $cword -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "list show start jump" -- "$cur") )
                elif [[ $cword -eq 3 ]]; then
                    case "${words[2]}" in
                    show|jump) _duct_complete_session_id ;;
                    start) _duct_complete_ticket_key ;;
                    esac
                fi
                ;;
            sync)
                [[ $cword -eq 2 ]] && COMPREPLY=( $(compgen -W "ci github jira sessions status workspace --force" -- "$cur") )
                ;;
            ticket)
                if [[ $cword -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "list open show" -- "$cur") )
                elif [[ $cword -eq 3 ]]; then
                    case "${words[2]}" in
                    open|show) _duct_complete_ticket_key ;;
                    esac
                fi
                ;;
            workspace)
                if [[ $cword -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "add-repo path status" -- "$cur") )
                elif [[ $cword -ge 3 ]]; then
                    case "${words[2]}" in
                    add-repo)
                        case $cword in
                        3) _duct_complete_ticket_key ;;
                        4) _duct_complete_repo_name ;;
                        esac
                        ;;
                    path)
                        [[ $cword -eq 3 ]] && _duct_complete_ticket_key
                        ;;
                    esac
                fi
                ;;
            esac
        }

        complete -o default -F _duct duct
    """)


def _fish_completion_script() -> str:
    return textwrap.dedent("""\
        # duct shell completion (fish)
        # Generated by: duct completion fish

        function __duct_find_workspace_root
            set -l dir (pwd)
            while test "$dir" != "/"
                if test -f "$dir/config.yaml"
                    echo "$dir"
                    return 0
                end
                set dir (dirname "$dir")
            end
            return 1
        end

        function __duct_complete_ticket_key
            set -l root (__duct_find_workspace_root); or return
            for entry in $root/[A-Z]*-[0-9]*
                test -d "$entry"; or continue
                set -l name (basename "$entry")
                string match -r '^([A-Z]+-[0-9]+)' -- "$name" | head -1
            end | sort -u
        end

        function __duct_complete_repo_name
            set -l root (__duct_find_workspace_root); or return
            set -l cache "$root/.cache/completions/repos.txt"
            test -f "$cache"; or return
            cat "$cache"
        end

        function __duct_complete_session_id
            set -l sessions_dir "$HOME/.claude/sessions"
            test -d "$sessions_dir"; or return
            for f in $sessions_dir/*.json
                test -f "$f"; or continue
                set -l pid (basename "$f" .json)
                kill -0 "$pid" 2>/dev/null; or continue
                set -l sid (grep -o '"sessionId"[[:space:]]*:[[:space:]]*"[^"]*"' "$f" 2>/dev/null | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/')
                test -n "$sid"; and echo (string sub -l 12 "$sid")
            end
        end

        # Disable default file completions
        complete -c duct -f

        # Top-level commands
        complete -c duct -n '__fish_use_subcommand' -a 'add-repo' -d 'Add a repo worktree'
        complete -c duct -n '__fish_use_subcommand' -a 'archive' -d 'Manage archived tickets'
        complete -c duct -n '__fish_use_subcommand' -a 'completion' -d 'Print completion script'
        complete -c duct -n '__fish_use_subcommand' -a 'config' -d 'Manage configuration'
        complete -c duct -n '__fish_use_subcommand' -a 'doctor' -d 'Check workspace health'
        complete -c duct -n '__fish_use_subcommand' -a 'init' -d 'Create workspace skeleton'
        complete -c duct -n '__fish_use_subcommand' -a 'orchestrate' -d 'Launch orchestrator'
        complete -c duct -n '__fish_use_subcommand' -a 'priority' -d 'View or edit priorities'
        complete -c duct -n '__fish_use_subcommand' -a 'session' -d 'Manage Claude sessions'
        complete -c duct -n '__fish_use_subcommand' -a 'status' -d 'Show status overview'
        complete -c duct -n '__fish_use_subcommand' -a 'sync' -d 'Run sync sources'
        complete -c duct -n '__fish_use_subcommand' -a 'ticket' -d 'List and inspect tickets'
        complete -c duct -n '__fish_use_subcommand' -a 'workspace' -d 'Manage workspaces'

        # completion
        complete -c duct -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'

        # ticket subcommands
        complete -c duct -n '__fish_seen_subcommand_from ticket; and not __fish_seen_subcommand_from list open show' -a 'list open show'
        complete -c duct -n '__fish_seen_subcommand_from ticket; and __fish_seen_subcommand_from open show' -a '(__duct_complete_ticket_key)'

        # archive subcommands
        complete -c duct -n '__fish_seen_subcommand_from archive; and not __fish_seen_subcommand_from add list restore' -a 'add list restore'
        complete -c duct -n '__fish_seen_subcommand_from archive; and __fish_seen_subcommand_from add restore' -a '(__duct_complete_ticket_key)'

        # session subcommands
        complete -c duct -n '__fish_seen_subcommand_from session; and not __fish_seen_subcommand_from list show start jump' -a 'list show start jump'
        complete -c duct -n '__fish_seen_subcommand_from session; and __fish_seen_subcommand_from show jump' -a '(__duct_complete_session_id)'
        complete -c duct -n '__fish_seen_subcommand_from session; and __fish_seen_subcommand_from start' -a '(__duct_complete_ticket_key)'

        # sync subcommands
        complete -c duct -n '__fish_seen_subcommand_from sync; and not __fish_seen_subcommand_from ci github jira sessions status workspace' -a 'ci github jira sessions status workspace'

        # priority subcommands
        complete -c duct -n '__fish_seen_subcommand_from priority; and not __fish_seen_subcommand_from add' -a 'add'
        complete -c duct -n '__fish_seen_subcommand_from priority; and __fish_seen_subcommand_from add' -a '(__duct_complete_ticket_key)'

        # orchestrate options
        complete -c duct -n '__fish_seen_subcommand_from orchestrate' -l ticket -a '(__duct_complete_ticket_key)'
        complete -c duct -n '__fish_seen_subcommand_from orchestrate' -l dry-run
        complete -c duct -n '__fish_seen_subcommand_from orchestrate' -l sync
        complete -c duct -n '__fish_seen_subcommand_from orchestrate' -l skip-permissions
        complete -c duct -n '__fish_seen_subcommand_from orchestrate' -s v -l verbose

        # add-repo positional args
        complete -c duct -n '__fish_seen_subcommand_from add-repo' -a '(__duct_complete_ticket_key)'
        complete -c duct -n '__fish_seen_subcommand_from add-repo' -a '(__duct_complete_repo_name)'

        # workspace subcommands
        complete -c duct -n '__fish_seen_subcommand_from workspace; and not __fish_seen_subcommand_from add-repo path status' -a 'add-repo path status'
        complete -c duct -n '__fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from path' -a '(__duct_complete_ticket_key)'
        complete -c duct -n '__fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from add-repo' -a '(__duct_complete_ticket_key)'
        complete -c duct -n '__fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from add-repo' -a '(__duct_complete_repo_name)'
    """)


@click.command()
@click.argument("shell", type=click.Choice(["bash", "zsh", "fish"]))
def completion(shell: str) -> None:
    """Print shell completion activation script.

    Add the output to your shell profile to enable tab completion:

        eval "$(duct completion zsh)"
    """
    generators = {
        "bash": _bash_completion_script,
        "zsh": _zsh_completion_script,
        "fish": _fish_completion_script,
    }
    click.echo(generators[shell]())


class LazyGroup(click.Group):
    """A click.Group that defers command imports until they are needed.

    During tab completion, only list_commands() is called (returning plain
    strings), so none of the heavy command modules are imported. When an
    actual command is invoked, get_command() imports just that one module.
    """

    def list_commands(self, ctx):
        return sorted(COMMANDS.keys()) + ["completion"]

    def get_command(self, ctx, cmd_name):
        if cmd_name == "completion":
            return completion
        if cmd_name not in COMMANDS:
            return None
        module_path, attr = COMMANDS[cmd_name].rsplit(":", 1)
        mod = importlib.import_module(module_path)
        return getattr(mod, attr)


@click.group(cls=LazyGroup)
@click.option("--json", "json_output", is_flag=True, help="Output as JSON.")
@click.option("--debug", is_flag=True, help="Show debug information.")
@click.option(
    "--workspace-root",
    type=click.Path(),
    default=None,
    help="Override workspace root directory.",
)
@click.pass_context
def cli(ctx: click.Context, json_output: bool, debug: bool, workspace_root: str | None) -> None:
    """duct — Developer workflow orchestration."""
    ctx.ensure_object(dict)
    ctx.obj["json"] = json_output
    ctx.obj["debug"] = debug
    ctx.obj["workspace_root"] = workspace_root
